# Generated by Django 4.1.1 on 2022-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecoverylink',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
