# Generated by Django 4.1.1 on 2022-09-30 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_passwordrecoveryhash_delete_passwordrecoverylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecoverycode',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordrecoverycode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovered_password_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordrecoveryhash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovered_password_hashes', to=settings.AUTH_USER_MODEL),
        ),
    ]
