# Generated by Django 4.1.1 on 2022-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_passwordrecoverycode_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecoveryhash',
            name='hash',
            field=models.CharField(max_length=255),
        ),
    ]
