# Generated by Django 4.1.1 on 2022-10-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_passwordrecoverylink_userverificationcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecoverylink',
            name='uid',
            field=models.CharField(default='salom', max_length=255),
            preserve_default=False,
        ),
    ]
