# Generated by Django 4.1.1 on 2022-10-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_passwordrecoverylink_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVerifyLink',
        ),
    ]
