# Generated by Django 4.1.1 on 2022-09-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelExtraFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HotelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('startCount', models.IntegerField()),
                ('description', models.TextField()),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelamenity')),
                ('extra_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelextrafeature')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelfeature')),
                ('locatedCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.country'),
        ),
    ]
