# Generated by Django 4.1.1 on 2022-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_room_roomfeature_roomimage_room_features_room_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfeature',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
