# Generated by Django 4.1.1 on 2022-10-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotelfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelamenity',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
